### ISSUE TITLE
Geth running out of memory on musicoin.org web site

### ISSUE THREAD

**Issue by immartian** [Musicoin/go-musicoin#10]
Although there's no direct evidence to link to memory leak of geth, it's a big concern to us to apply geth as major client of musicoin community. It's easy to trigger the whole network into a havoc if it's not fully safeguarded.

**Comment by immartian** [comment]
The earlier memory leak of Geth was reported at https://github.com/ethereum/go-ethereum/issues/3002 but not sure if the most recent one has new flaws found in our case.

**Comment by immartian** [comment]
I also met a Parity crash the other day after some overloaded RPC call, so there's another possibility that the RPC interface may cause some panic as well, though most frequent RPC calls are read-only operations.

**Comment by musicoiner** [comment]
not appearing again, close now.
