### ISSUE TITLE
A boring ghost chain

### ISSUE THREAD

**Issue by immartian** [Musicoin/go-musicoin#12]
Don't understand, there's always a lower height block being mined even the height blockchain has been mined very tall. 

![image](https://cloud.githubusercontent.com/assets/81030/22433738/60b6caf4-e754-11e6-8fd1-73a36aa3cfa7.png)

**Comment by phiferd** [comment]
I think this issue is actually a printing/flushing issue.  I have yet to see an example where the block number referenced does not happen to be a prefix of the correct block number.

![image](https://cloud.githubusercontent.com/assets/25631/22448785/abd92706-e796-11e6-9e7f-0bae3b14cc51.png)


Unfortunately, our logs are not going into a file (as far as I can tell) so we can't grep for a complete history.

**Comment by phiferd** [comment]
Ah, also note these lines in my screen shot, showing the word "**confirmatio**" (missing the "n"), although other lines show the full word:

> I0131 01:15:09.123630 miner/worker.go:342] 🔨  Mined block (#20209 / 5eb067d1). Wait 5 blocks for confirmatio
I0131 01:15:09.124811 miner/worker.go:539] commit new work on block 20210 with 2 txs & 1 uncles. Took 1.104329ms
I0131 01:15:09.124874 miner/worker.go:435] 🔨 🔗  Mined 5 blocks back: block #202
I0131 01:15:09.126401 miner/worker.go:539] commit new work on block 20210 with 2 txs & 1 uncles. Took 1.05576

**Comment by immartian** [comment]
I'm asking a guy, his response:
"And Blockchain is not functioning properly. Interestingly, I had a similar experience. In fact, this "block back" feature is a powerful feature that prevents dangers such as net attacks. But you have "block back 186" as a constant. In my case this number was variable(this was also a problem). In my case debugging solved the error. Perhaps your case also needs debugging. This problem can be solved.

I would first recommend that Musicoin's directory not be duplicated with Ethereum. Duplicating Ethereum sometimes makes debugging confusing. Of course, it does not matter if you do not run Ethereum at least once. And please note that I'm not analyzing or testing all the source code for musicoin, so there may be other problems.
"

**Comment by phiferd** [comment]
Using a branch, we confirmed this is an issue with printing.  I printed the block number in the log line twice, once early in the string and once at the end, and got this:

> I0131 02:31:07.543604 miner/worker.go:539] commit new work on block 20491 with 0 txs & 0 uncles. Took 199.953µs
I0131 02:31:07.543714 miner/worker.go:435] 🔨 🔗  checking block #**20485**. Mined 5 blocks back: block #**204**
I0131 02:31:10.000260 core/blockchain.go:1001] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 2.76006ms. #20491 [c41ab71e / c41ab71e]

**Comment by immartian** [comment]
solved with this https://github.com/Musicoin/go-musicoin/pull/13
