### ISSUE TITLE
Can not be installed correctly

### ISSUE THREAD

**Issue by ooof** [Musicoin/go-musicoin#14]
#### System information

Geth version: `gmc-windows-4.0-386.exe`
OS & Version: Windows10
Commit hash : (if `develop`)

#### Expected behaviour

installation

#### Actual behaviour

![12](https://cloud.githubusercontent.com/assets/392785/22869748/3affb284-f1dc-11e6-969c-4c5f5df1564e.PNG)

#### Backtrace

````
[backtrace]
````

**Comment by immartian** [comment]
pls use https://github.com/Musicoin/desktop/releases , which is better for common users

**Comment by phiferd** [comment]
Right -- so I think you downloaded the command line tool (which appears to be running fine from the screenshot, so that's good).  As @immartian said, the Musicoin/desktop tool includes a UI as well, which is what you were expecting I think.

**Comment by ooof** [comment]
I downloaded from here: https://github.com/Musicoin/go-musicoin/releases

Maybe wrong, I try for a try.

**Comment by immartian** [comment]
https://github.com/Musicoin/desktop/releases
