### ISSUE TITLE
I do not know what to do.

### ISSUE THREAD

**Issue by ooof** [Musicoin/go-musicoin#15]
#### System information

Geth version: `geth version`
OS & Version: Windows10
Commit hash : (if `develop`)

#### Actual behaviour

![Uploading 66.PNG…]()

#### Backtrace

````
[backtrace]
````

**Comment by immartian** [comment]
download another app, not this, you better use the simplest one:
https://github.com/Musicoin/desktop/releases

**Comment by ooof** [comment]
In the state of mining.
