### ISSUE TITLE
How about add pool list in WiKi threads?

### ISSUE THREAD

**Issue by trustfarm-dev** [Musicoin/go-musicoin#17]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by immartian** [comment]
good idea, @trustfarm-dev 
 @Chance567 , love to make one page and put a link on homepage?

**Comment by trustfarm-dev** [comment]
I've already running a musicoin pool from 50000 blocks,

my pool address is here.

http://mc.trustfarm.io/
or 
http://musicoin.trustfarm.io/

please add wiki pool lists.

**Comment by Chance567** [comment]
Added to wiki. Thanks for bringing it to my attention! 

    On Monday, March 13, 2017 10:21 PM, Trustfarm-heart <notifications@github.com> wrote:
 

 I've already running a musicoin pool from 50000 blocks,my pool address is here.http://mc.trustfarm.io/
or
http://musicoin.trustfarm.io/please add wiki pool lists.—

**Comment by trustfarm-dev** [comment]
@Chance567 thanks a lot!

**Comment by Deekor** [comment]
I've set up a pool at: http://www.rig-share.com/pools/music could you please add it?

**Comment by eros1453** [comment]
I have a musicoin pool operating for over 1 month.
The address is : mscams.globalmine.net
The server is located in amsterdam europe.
Has a good ping time and uptime.
Please add to wiki pool list.
Thank you.

**Comment by frankurcrazy** [comment]
Hi, I have a musicoin pool in Taiwan with high availability which charges zero fee and sends payout every hour.
The pool address is: http://pool.musicoin.tw
The server is located at Taiwan

Please add to wiki pool list
Thanks

**Comment by immartian** [comment]
both will be added soon.

**Comment by frankurcrazy** [comment]
@immartian Thanks!!

**Comment by etherninja** [comment]
Hello. I operate a musicoin pool gmc.epool.io 

gmc.epool.io Operator @epool.io

May I have add to wiki pool list please

**Comment by Varunram** [comment]
Done

**Comment by Pcmode** [comment]
Please add the first pool and still a huge supporter of Musicoin. Musicoin.nomnom.technology. 
Thanks!

**Comment by zet-tech** [comment]
Hi,

Also would be great to be listed:


https://mc.zet-tech.eu/#/


Operator: ZET Technologies

*ZET Team*

*ŻET*
Digital Technologies

*Poznan University of Technology*
*Street:  Piotrowo 3B*
*Zip Code: 61-138 Poznan, Poland*

*Phone number:* : +48 535 495 762
*E-mail*: info@zet-tech.eu
*Facebook*: https://www.facebook.com/zet.tech.eu/
*Twitter*:  https://twitter.com/ZET_mining
*VAT ID*: PL 672 201 1950





2017-09-10 6:25 GMT+02:00 Varunram Ganesh <notifications@github.com>:

**Comment by Varunram** [comment]
I've opened an issue over at #39 where miners can request that their pols be added (and also to edit wrong information, if any).

**Comment by techievee** [comment]
We are proud to announce First ever *Dynamic PPLNS* mining Pool for altcoins ( https://daggerpool.com ) .Music Coinis listed in our Pool

**Pool Features**

* 0% Pool fees as Introductory Offer
* First time ever Fair and Profitable  "Dynamic PPLNS Payout Scheme", where 'N' value for each round gets adjusted dynamically based on the Chain Difficulty
* Automatic Payouts every 2 hours
* Customizable payout threshold values
* Full Stratum Support 
* Highly Efficient Mining Engine (Completely refactored code of Sammy Libre's open-ethereum-pool)
* open source mining engine
* Completely open front end statistics showing - Pool Address, Total Shares submitted, Current shares active in last N buffer etc
* Server located at US Central 
* More servers are planned for future
* Real time token value conversion in USD
* Professional Helpdesk

**Try our pool few days continuously and see the difference in earning**

*PPLNS Scheme yields more profit for the miners who are mining in a single pool, Pool wont favour pool hoppers, Earning increases gradually with time*

https://daggerpool.com

https://music.daggerpool.com

**Comment by daggerpool** [comment]
We are proud to announce First ever *Dynamic PPLNS* mining Pool for altcoins ( https://daggerpool.com ) .Music Coin in listed in our Pool

**Pool Features**

* 0% Pool fees as Introductory Offer
* First time ever Fair and Profitable  Dynamic PPLNS Payout Scheme, where 'N' value for each round gets adjusted dynamically based on the Chain Difficulty
* Automatic Payouts every 2 hours
* Customizable payout threshold values
* Full Stratum Support 
* Highly Efficient Mining Engine (Completely refactored code of Sammy Libre's open-ethereum-pool)
* open source mining engine
* Completely open front end statistics showing - Pool Address, Total Shares submitted, Current shares active in last N buffer etc
* Server located at US Central 
* More servers are planned for future
* Real time token value conversion in USD
* Professional Helpdesk

**Try our pool few days continuously and see the difference in earning**

*PPLNS Scheme yields more profit for the miners who are mining in a single pool, Pool wont favour pool hoppers, Earning increases gradually with time*

https://daggerpool.com
https://music.daggerpool.com
