### ISSUE TITLE
Cannot start mining without etherbase address: etherbase address must be explicitly specified

### ISSUE THREAD

**Issue by Deekor** [Musicoin/go-musicoin#18]
I've set my etherbase via the console `miner.setEtherbase(MY_ACCOUNT)` and then leave the console and start up rpc. Once my miner connects the screen floods with the error:

    eth/cpu_mining.go:35] Cannot start mining without etherbase address: etherbase address must be explicitly specified

What am I doing wrong here?

**Comment by immartian** [comment]
What system?

**Comment by Deekor** [comment]
Ubuntu

**Comment by lambda-knight** [comment]
I've encountered the same error.

**Comment by immartian** [comment]
I think you need to create a local account with 
`personal.newAccount()`

**Comment by Varunram** [comment]
@Deekor I'm closing this issue assuming this has been resolved. If the problem still persists, feel free to comment on this thread and I shall re-open it.

**Comment by simon-brooke** [comment]
I can confirm that

1. I had this problem (also Ubuntu, but not sure that's relevant);
2. entering `personal.newAccount()` in the the Geth JavaScript console solved it.

**Comment by jjziets** [comment]
So the account must be local? can not use an exchanged address to solomine?

**Comment by mikhailrojo** [comment]
the unique way to solve it, is to set an address in console mode of geth?
can it be done via RPC?

**Comment by Sashom** [comment]
./new_account.sh
then instead of "node0, 1, 2..." put "miner" to fill the keystore folder of the "miner"

**Comment by gzw13999** [comment]
miner.setEtherbase("0x.............................................")
