### ISSUE TITLE
Help commands?

### ISSUE THREAD

**Issue by Alkaris** [Musicoin/go-musicoin#19]
This really needs some proper documentation on the available commands and cvars, because as it currently is, it's really confusing and difficult to know what all the commands are, and all the cvar functions of a command you want to execute.

a simple `help` cvar would just be really simple enough to add so you can list all the available cvars as well as the functions that can be passed to them. Because3 simply typing in random stuff isn't good enough and guessing what kind of cvars you need to type to make the command you want to work.

like this for example
```
admin.getContractInfo function()
```

What even? So that's why this could really do with a help cvar of what these sort of commands expect, and I see that it does use JavaScript mixed with JSON type cvar stuff and that can be quite confusing.

**Comment by TBJack027** [comment]
Maybe the help from go-ethereum can help you~
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#adminimportchain

**Comment by Varunram** [comment]
Hi @Alkaris, all `geth` command apply to the `gmc` console as well and you can refer to the Admin pages on the `geth` wiki for the same.
