### ISSUE TITLE
No command 'gmc' found, but there are 23 similar ones

### ISSUE THREAD

**Issue by alptolga** [Musicoin/go-musicoin#20]
When I try to run gmc I got this error. I use ubuntu 16.04
~/go-musicoin$ gmc console
No command 'gmc' found, but there are 23 similar ones
gmc: command not found

**Comment by immartian** [comment]
$ ./gmc console

**Comment by alptolga** [comment]
Thanks for your reply. I can run gmc only from /go-musicoin/build/bin$
