### ISSUE TITLE
make gmc-cross

### ISSUE THREAD

**Issue by Surfang** [Musicoin/go-musicoin#29]
#### System information

OS & Version: Linux(ubuntu 16.04)
Commit hash : (if `develop`)

build/env.sh go run build/ci.go xgo -- --go=latest --dest=build/bin --targets=linux/386 -v ./cmd/gmc
unexpected directory layout:
        import path: _/home/dz/musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
        root: /home/dz/musicoin/build/_workspace/src
        dir: /home/dz/musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
        expand root: /home/dz/musicoin/build/_workspace/src
        expand dir: /home/dz/musicoin/internal/build
        separator: /
Makefile:45: recipe for target 'gmc-linux-386' failed
make: *** [gmc-linux-386] Error 1

**Comment by immartian** [comment]
There's many such report from different communities about this issue which has to blame Golang. 
Currently, you have to downgrade your golang to <1.8 to build this package. Later we will upgrade the package to support v1.8 though.

**Comment by Varunram** [comment]
HI there! This is a known bug with Go 1.8 and the gaoling team is working on the same. A fix would be to remove Go 1.8 and install Go 1.7 (lesser versions would not work since ifs requires Go 1.7)
