### ISSUE TITLE
MEW and Trezor security concern, with EIP 155 implementation

### ISSUE THREAD

**Issue by immartian** [Musicoin/go-musicoin#30]
As pointed by https://github.com/kvhnuke/etherwallet/issues/912#issuecomment-323617796  we may need to consider a fast-forward implementation with EIP 155 before UBI. It seems time is quite limited, so another option is to put to v2.x . 

Really appreciate MEW community to point this out.

**Comment by trustfarm-dev** [comment]
https://github.com/trezor/trezor-mcu/pull/212/files/1984a7675b4c7edf18b5aa1cf16c894eb82d153a#diff-12950855dc4a2a268fb19ece6da37668

EIP 155 doesn't applied on GMC. 
So, I applied MUSICoin on MEW, with EIP 155 supports False on MEW. 
In case of Musicnode has replay protection contract , then It will be protecting replay attack.
Early method of ETC has forked.
