### ISSUE TITLE
Make problem

### ISSUE THREAD

**Issue by minitzi** [Musicoin/go-musicoin#33]
#### System information
 Ubuntu 16.04.2 LTS
Geth version: `geth version`
go version go1.9 linux/amd64
OS & Version: Windows/Linux/OSX
Linux NextPool 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux

root@NextPool:~/go-musicoin# make
build/env.sh go run build/ci.go install ./cmd/gmc
unexpected directory layout:
        import path: _/root/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
        root: /root/go-musicoin/build/_workspace/src
        dir: /root/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
        expand root: /root/go-musicoin/build/_workspace/src
        expand dir: /root/go-musicoin/internal/build
        separator: /
Makefile:16: recipe for target 'gmc' failed
make: *** [gmc] Error 1
root@NextPool:~/go-musicoin#

Do you have any idee where is the problem ?
Thanks

**Comment by Varunram** [comment]
Hey there! Please compile with Go1.7 or lower. Go 1.8+ has a bug with our make process. Let me know if it works

**Comment by Varunram** [comment]
Just recompiled gmc1.5 on `go-1.7 linux/amd64`. Closing this issue for now.
