### ISSUE TITLE
running nodes for some reasons gets Killed

### ISSUE THREAD

**Issue by jjziets** [Musicoin/go-musicoin#37]
my nodes is running :-) well still syncing but there seems to be hope.

but for some reason, it is getting killed

#### System information

Geth version: `geth version` latest
OS & Version: Windows/Linux/OSX Ubunto 16.04 

#### Expected behaviour
Run in screen non stop 

#### Actual behaviour
Gets killed. 
![image](https://user-images.githubusercontent.com/19214485/30232410-3b82dfc6-94f0-11e7-9ac2-c96bea4d6679.png)

#### Steps to reproduce the behaviour
screen 

./gmc --rpc --rpcaddr 172.31.34.201 --rpcport 8545  console

#### Backtrace

````
[backtrace]
````

**Comment by immartian** [comment]
what's the version number after running `gmc version` ?

**Comment by jjziets** [comment]
i deleted the go-musicoin folder and did a sudo git clone https://github.com/Musicoin/go-musicoin.git

instance: GMC/v2.0.0-stable-d849d276/linux/go1.6.3

**Comment by immartian** [comment]
so you did `make gmc`, please make sure Go version under 1.8 (the released version was built with Go 1.7.3, fyi)

**Comment by jjziets** [comment]
that could bit. yes i did make gmc but have not been bale to ge go1.8 to install on the ubuntu.

**Comment by Varunram** [comment]
`gmc` does not work with Go1.8. Please report back after building on go1.7.3. Thanks!

**Comment by jjziets** [comment]
Ok brand new vps with ubuntu 16.04 go 1.7.3 
vps has 1GB ram and 30Gb hdd

./gmc version
GMC
Version: 2.0.0-stable-d849d276
Protocol Versions: [63 62]
Network Id: 7762959
Go Version: go1.7.3
OS: linux
GOPATH=/home/ubuntu/work
GOROOT=/usr/local/go



        /home/ubuntu/work/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:431 +0x1e9

goroutine 19191 [chan receive]:
github.com/ethereum/go-ethereum/p2p/discover.(*Table).pingpong(0xc420216d00, 0xc4316de200, 0xdbe2173cda46d300, 0xfb5b5751b1076f9f, 0xd7da37df59fb79f0, 0x1a337db835366301, 0xd62553f6f122ce17, 0x3daa1cbd29570dd7, 0x510d97d5be0334e0, 0x16ba6c6a5704f2f2, ...)
        /home/ubuntu/work/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:511 +0x58
github.com/ethereum/go-ethereum/p2p/discover.(*Table).bond(0xc420216d00, 0xdbe2173cda46d300, 0xfb5b5751b1076f9f, 0xd7da37df59fb79f0, 0x1a337db835366301, 0xd62553f6f122ce17, 0x3daa1cbd29570dd7, 0x510d97d5be0334e0, 0x16ba6c6a5704f2f2, 0xc42dd71f3c, ...)
        /home/ubuntu/work/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:487 +0x735
github.com/ethereum/go-ethereum/p2p/discover.(*Table).bondall.func1(0xc420216d00, 0xc42fa74ea0, 0xc430bdaa80)
        /home/ubuntu/work/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:432 +0xde
created by github.com/ethereum/go-ethereum/p2p/discover.(*Table).bondall
        /home/ubuntu/work/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:434 +0xa5

goroutine 19164 [chan receive]:
github.com/ethereum/go-ethereum/p2p/discover.(*Table).bondall(0xc420216d00, 0xc4272f6080, 0x10, 0x10, 0x6aa8881073a9cdea, 0xeeb0b8619b6b67d1, 0x80d5419e0b204f76)
        /home/ubuntu/work/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:437 +0x118
github.com/ethereum/go-ethereum/p2p/discover.(*Table).lookup.func1(0xc420216d00, 0xc43ac4f780, 0xc4274bdb40, 0xc42f3b74a0)
        /home/ubuntu/work/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:288 +0x1a6
created by github.com/ethereum/go-ethereum/p2p/discover.(*Table).lookup
        /home/ubuntu/work/go-musicoin/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:289 +0x478

**Comment by jjziets** [comment]
it runs for a few blocks and then I get that message

**Comment by immartian** [comment]
can you try to build again on the server with most recent commit?  
Also please remove ~/.musicoin/chaindata and try again.

**Comment by jjziets** [comment]
I deleted the AWS EC2 vps and start a new one from scratch.  1GB Ram, 30GB SSD(Free Tair)
Ubuntu 16.04 


$sudo apt-get update
$sudo apt install make
$sudo apt install gcc
$wget https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz
$sudo tar -zxvf go1.7.3.linux-amd64.tar.gz -C /usr/local
$mkdir work
$export PATH=$PATH:/usr/local/go/bin
$export GOPATH=$HOME/work 
$cd work
$git clone https://github.com/Musicoin/go-musicoin.git
$cd go-musicoin/  
$make gmc  
$cd build/bin
$./gmc version
GMC
Version: 2.0.0-stable-d849d276
Protocol Versions: [63 62]
Network Id: 7762959
Go Version: go1.7.3
OS: linux
$screem
$./gmc --rpc --rpcaddr 172.31.20.154 --rpcport 8545  console

So far it looks like it is syncing. now at block 297642 but is is only adding 1 block ever min. so something must be wrong.

$ free
                 total               used        free      shared  buff/cache   available
Mem:        1014660      734728      112428        3148      167504      120592
Swap:       4194300           0           4194300

The block explorer shows that block height to be 10k and I am at 3k?

**Comment by immartian** [comment]
It's good to see it's syncing although the speed is not ideal but seems not a big issue.  Some others sync slower these 2 days.

**Comment by jjziets** [comment]
yea it is syncing. now at 630968. adds about 10-50 blocks every few seconds.
