### ISSUE TITLE
GMC client with UBI Scheme (V2.0.0)

### ISSUE THREAD

**Issue by igotfits1** [Musicoin/go-musicoin#38]
hey team was wondering if you can give a small tutorial on installing this stuff, im running windows 10 64bit, i downloaded the windows .exe. When i fire up the exe it opens cmd prompt and just imports blocks, im not sure if im doing what im suppose to be doing. I go my old go-musicoin client folder and only the gmc.exe is in there compared to the go-musicoin 2.0.0 folder i downloaded which has a ton of folders. thanks again in advance, im still new to all this and been only mining for a few weeks.

**Comment by igotfits1** [comment]
will downloading wallet .7 avoid all this hassle?

**Comment by immartian** [comment]
0.7 upgrades blockchain together,so try it and report back?
