### ISSUE TITLE
MUSIC 2.0 crashes after a few hours

### ISSUE THREAD

**Issue by Deekor** [Musicoin/go-musicoin#40]
Ubuntu 16.04.2 x64

Since updating to Music 2.0 my node consistently crashes. I've been running my pool for 5 months on the old version without a single crash.

I was on `Go 1.6.2` and thought that might be the problem so I updated to `Go 1.7.3` and the crash still occurs.

Do I need to rebuild after updating Go?

![screen shot 2017-09-15 at 8 20 47 am](https://user-images.githubusercontent.com/1904267/30487621-379eb7d0-99f1-11e7-8f6b-fc9700498c51.png)

**Comment by immartian** [comment]
It's not so clear to me the real reason behind it but still suspect it's related to Go. Link the previous reports first to see if community can help. https://github.com/Musicoin/go-musicoin/issues/37

**Comment by Deekor** [comment]
Re-compiled after installing Go 1.7.3 and it still crashed.

**Comment by immartian** [comment]
New version to fix old issues. Can build with Go 1.8+.
