### ISSUE TITLE
gpu not functioning NEED BUILD RELEASE WITH OPENCL ADDED PLEASE

### ISSUE THREAD

**Issue by Horsetoothless** [Musicoin/go-musicoin#41]
#### System information have amd rx-460 8 gig gpu works with nicehash
PROGRAM WITH NAME AMD64 SHOULD HAVE GPU INSTALLED ALREADY SET  "OPENCL" AND REBUILD
'I will try but am a newbie here'

GMC version: `gmc version4.0AMD64`
OS & Version: Windows10
Commit hash : (if `develop`)cpu only hashing works great but don't want to burn it up, 100% usage

####all attempts of  gpuinfo, gpubench,--minergpus 0, are not recognized by program but are listed in help file, set GO_OPENCL and re-build to enable

#### Backtrace looking forward to do some mining here.

````
[backtrace]
````

**Comment by Varunram** [comment]
@Horsetoothless Please look at the "Start a miner" section of the wiki to get started on mining with the gpu.
