### ISSUE TITLE
Upgrade GMC to be compatible with Go1.8+

### ISSUE THREAD

**Issue by immartian** [Musicoin/go-musicoin#45]
<a href="https://github.com/Varunram"><img src="https://avatars1.githubusercontent.com/u/18598959?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Varunram](https://github.com/Varunram)**
_Sunday Sep 03, 2017 at 07:08 GMT_
_Originally opened as https://github.com/Musicoin/PM/issues/118_

----

Golang is on the route to Go2.0 and we should make sure that `gmc` successfully builds with all future versions of Go. We can keep this as a priority after UBI.

**Comment by immartian** [comment]
<a href="https://github.com/immartian"><img src="https://avatars2.githubusercontent.com/u/81030?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [immartian](https://github.com/immartian)**
_Sunday Oct 01, 2017 at 02:41 GMT_

----

Will move this out to go-musicoin repo, close now.

**Comment by 5chdn** [comment]
I highly encourage you to run a recent fork of go-ethereum as soon as possible :)

**Comment by immartian** [comment]
Yes, time to do so
