### ISSUE TITLE
Running Parity with $MUSIC 2.0

### ISSUE THREAD

**Issue by immartian** [Musicoin/go-musicoin#47]
There's an non-official version of Parity-derivative at https://github.com/immartian/rmc , we are working toward to merge into Parity with the helps of ParityTech team.  https://github.com/paritytech/parity/pull/6621 

However, there must be an explicit statement within spec to run Parity with GMC compatibility, which is  `"homesteadTransition": "0x118c30"` to prevent the sync stuck at 1,150,000, otherwise it's all ok.

**Comment by immartian** [comment]
The newest spec can be found here: https://github.com/immartian/rmc/releases/tag/V0.1.0

**Comment by 5chdn** [comment]
fixed in https://github.com/paritytech/parity/commit/072ba1d1109c9c5b1eb1f61dba67adf769eb7c42

chainspec for 1.8 available here https://github.com/paritytech/parity/blob/a5-chains-musicoin/ethcore/res/ethereum/musicoin.json

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity/pull/6621 merged

**Comment by 5chdn** [comment]
Done. 

https://github.com/paritytech/parity/releases/tag/v1.8.0

**Comment by immartian** [comment]
Cograt and so grateful. Close this successfully.
