### ISSUE TITLE
make: *** No rule to make target 'gmc'.  Stop.

### ISSUE THREAD

**Issue by bapparabi** [Musicoin/go-musicoin#48]
make gmc
make: *** No rule to make target 'gmc'.  Stop.

how to solve this iisue

**Comment by immartian** [comment]
version of Golang?

**Comment by bapparabi** [comment]
go1.7.1 this version i have

**Comment by immartian** [comment]
Your GOPATH may not correctly set:  https://github.com/kubernetes/kubernetes/issues/28987

**Comment by bapparabi** [comment]
no installation working .. can you guide me any installation to do this ..

**Comment by Varunram** [comment]
In which directory are you in? Here is a useful pointer on how to set GOPATH: https://golang.org/doc/install

**Comment by bapparabi** [comment]
yes i use everything but not working

**Comment by Varunram** [comment]
Could you check your working directory again, please?

**Comment by bapparabi** [comment]
root@localhost:~# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build920463922=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
root@localhost:~#

**Comment by Varunram** [comment]
I think you're in the wrong directory. Please navigate to the correct directory and try again. Also, your GOPATH is set to /root/work which you might want to change.

**Comment by immartian** [comment]
Please build the newest version. It's directory now aligns with Go 1.8+.
