### ISSUE TITLE
Block rewards are not changing after config

### ISSUE THREAD

**Issue by Thomasmcdaniel9** [Musicoin/go-musicoin#51]
hey guys we have the config like this  but the block rewards are not chaning over to 314 is this correct 
var constReward = math.MustParseBig256(“5000000000000000000”)

var uncleReward = new(big.Int).Div(constReward, new(big.Int).SetInt64(32))

// Donate 10% from pool fees to developers

const donationFee = 10.0

const donationAccount = “0xb85150eb365e7df0941f0cf08235f987ba91506a”

Changed file:

var constReward = math.MustParseBig256(“314000000000000000000”)

var uncleReward = new(big.Int).Div(constReward, new(big.Int).SetInt64(32))

#### System information

GMC version: `gmc version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by trustfarm-dev** [comment]
@Thomasmcdaniel9 As we discussed in slack, check missing with your friends. above code has no problem as review.
And, SHOULD be change the 314 -> 250. prepare pool sw. and using it when 12000000 block heights.

var constReward = math.MustParseBig256(“250000000000000000000”)

**Comment by Thomasmcdaniel9** [comment]
Ok hey if your gonna be up ill have my friend contact you that way he can get a better understanding. But thank you for the help talk with you soon

**Comment by immartian** [comment]
close for now. New version GMC is going to release(v2.1 or v2.5)
