### ISSUE TITLE
make release gmc node name to indicate what version of binary.

### ISSUE THREAD

**Issue by trustfarm-dev** [Musicoin/go-musicoin#53]
#### System information

GMC version: `gmc version`
OS & Version: Windows/Linux/OSX
Commit hash : 

#### Expected behaviour
Now, current release filename is same with all version.
release name is "gmc-linux-amd64"
missing the download file version checking, it may be using old version's gmc node.

please making compress and file name will include version or git tag number, for not confusion what using version of sw.

#### Backtrace

````
[backtrace]
````

**Comment by immartian** [comment]
Will be added in upcoming new version.
