### ISSUE TITLE
GMC -V3, need to check licenses term.

### ISSUE THREAD

**Issue by trustfarm-dev** [Musicoin/go-musicoin#60]
#### System information

GMC version: gmc v3.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
There's need to printing License term , to GPL or LGPL, MIT or Apache, ...

#### Actual behaviour
run gmcv3 --help 
NAME:
   gmcv3 - the go-ethereum command line interface
   Copyright 2013-2017 The go-ethereum Authors
...
 VERSION:
   2.1.0-unstable-b0f741e8

or gmcv3 license
GMC is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

#### Steps to reproduce the behaviour
Just built and Run

Recommendation, Add GPL license term to gmcv3 printing.

**Comment by 5chdn** [comment]
> There's need to printing License term , to GPL or LGPL, MIT or Apache, ...

Why? It's in the repository in all source files and the readme already. There is a copyright notice at the end of `--help`.

**Comment by trustfarm-dev** [comment]
@5chdn I know, also, gmcv3 license shows GPL well.
I recommend to sync printing.

**Comment by 5chdn** [comment]
This will get messy because GMC is licensed under two different licenses. The copyright notice is sufficient in my eyes.
