### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by trustfarm-dev** [Musicoin/go-musicoin#65]
#### System information

GMC version: `gmc v30`
OS & Version: Linux Ubuntu 16.04 (upgrade from 14.04)
Commit hash : (if `develop`)

#### Actual behaviour
node down with following logs
d4ffe800bc30e3d827@[::]:30314
Fatal: Error starting protocol stack: listen tcp :30314: socket: too many open files

#### Steps to reproduce the behaviour
full sync mode

#### reference informations
Above issue already discussed in early season of ethereum (frontier and homestead era) .
I've expanding and tune up my system ulimit and kernel property.
there's still occur, Is there more helpful guide to me.

**Comment by 5chdn** [comment]
Google "your OS" + "too many open files" ;)

**Comment by trustfarm-dev** [comment]
I've already tune and searched google , but there's still issues.

**Comment by 5chdn** [comment]
Yeah but that's an OS issue not a GMC issue :)

**Comment by SharkWipf** [comment]
I'm not sure it is actually. I'm getting the same issue, I have all ulimit/max files set to unlimited or close to it, the OS has 800 files open before I launch it, so the 1040 file handles it tries to open shouldn't be a problem.  
Somehow, it seems this problem only appears when it has trouble connecting to the network and when it happens the file handles it opens spikes sharply above 1040 before crashing. I've seen it jump to 3000+ open files even, presumably it spikes even higher but without logging open file handles to the millisecond or attaching a debugger it's hard to say for sure.  
I've seen similar issues with leaking file handles reported in older versions of upstream Geth, so I'm pretty sure it's not an OS configuration problem in this case.

**Comment by SharkWipf** [comment]
It seems you're also leaking this error on your website btw, this is what you find when googling "musicoin too many files open":  
![screenshot_20171104-145502_01](https://user-images.githubusercontent.com/751205/32406001-817f4a76-c170-11e7-9cbd-87eca04e0a30.jpg)  
(Error is gone on the live site, only still in the Google cache)

**Comment by 5chdn** [comment]
Ouch :D
