### ISSUE TITLE
Unable to start payouts, number of peers on a node is less than required 25

### ISSUE THREAD

**Issue by bapparabi** [Musicoin/go-musicoin#68]
Unable to start payouts, number of peers on a node is less than required 25

2017/11/19 14:49:54 Paid total 0 Shannon to 0 of 1 payees
2017/11/19 14:50:54 Unable to start payouts, number of peers on a node is less than required 25
2017/11/19 14:50:54 Paid total 0 Shannon to 0 of 1 payees
2017/11/19 14:51:54 Unable to start payouts, number of peers on a node is less than required 25
2017/11/19 14:51:54 Paid total 0 Shannon to 0 of 1 payees

my blockchain is already sync but still this problem happening ..do you know what iisue and how to solve it

**Comment by immartian** [comment]
what instruction you executed?

**Comment by bapparabi** [comment]
solved that by reducing the peers limit as 2 in payout file
