### ISSUE TITLE
[Feature] Creating packages for various distros

### ISSUE THREAD

**Issue by Varunram** [Musicoin/go-musicoin#71]
Creating packages would greatly simplify the need for looking into the various available releases. Requires maintaining with versions, but that should be possible.

**Comment by Varunram** [comment]
Requires integration to be setup via https://snapcraft.io. Will do for upcoming releases and close

**Comment by Varunram** [comment]
ppa integration done by @cryptofuture. Snap build paused for now due to buggy stuff on their side.

**Comment by etaletai13** [comment]
PPA, so you're saying you want the app published for package managers and installers and all that? I'll pop something together ... I would think it would be a totally pre-existing thing, but it doesn't look that way.
