### ISSUE TITLE
Withdrawal Issue

### ISSUE THREAD

**Issue by anjdeba** [Musicoin/go-musicoin#72]
hi,
i did a transfer using tx 0xee5cc1f6c4ec9a88c65cd8354ab427a9a3ea64649e760ab481604a7398437386

complete details are not visible at https://orbiter.musicoin.org/tx/0xee5cc1f6c4ec9a88c65cd8354ab427a9a3ea64649e760ab481604a7398437386

pls assist 

Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

GMC version: `gmc version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by anjdeba** [comment]
hi , can anyone help here pls ?

**Comment by immartian** [comment]
the transaction is visible on both explorer.musicoin.org and orbiter.musicoin.org. Not sure your question.
