### ISSUE TITLE
Provide diff for code verification

### ISSUE THREAD

**Issue by Varunram** [Musicoin/go-musicoin#75]
Requests for this have been there for a long time and now that we're incorporating changes from upstream geth, I think it would be better to provide a diff comparing against the latest version of geth so that people can compare stuff and see what parts of the codebase we've changed.

**Comment by XhmikosR** [comment]
Can't you keep an upstream branch and just make your changes in master/custom or whatever branch?

**Comment by Varunram** [comment]
Ah, I guess that should be possible. @5chdn what do you think?

**Comment by 5chdn** [comment]
I don't understand what this is about. #57 #66 #67 #69 #77 ?

**Comment by Varunram** [comment]
I think what XhmikosR meant really was whether we could have a branch with
geth (say at branch "upstream") and maintain gmc at say "master" so that
viewing diff becomes easier (instead of the PRs themselves)

**Comment by XhmikosR** [comment]
Yup, exactly ^^.

**Comment by 5chdn** [comment]
https://github.com/Musicoin/go-musicoin/compare/go-ethereum...master
