### ISSUE TITLE
GMC 2.0 is not compatible with 2.5

### ISSUE THREAD

**Issue by immartian** [Musicoin/go-musicoin#78]
I didn't expect this happened at 1,920,000 then found GMC 2.5 and 2.0 are totally incompatible. 
So for both Bittrex and Cryptopia , they were not running GMC2.5 before and stuck there since yesterday. 

We have suggested them to upgrade and seems Cryptopia succeed, but Bittrex didn't get through with the following errors:

```
ERROR[02-08|03:44:43]
########## BAD BLOCK #########
Chain config: {ChainID: 7762959 Homestead: 1150000 MCIP3-UBI: 1200001 DAO: 36028797018963967 DAOSupport: false EIP150: 36028797018963967 EIP155: 36028797018963967 EIP158: 36028797018963967 Byzantium: 36028797018963967 Engine: ethash}

Number: 1630914
Hash: 0x9281bc547ebe41b641b1533e3d642e7db6a436a5558ba20a4beff4b3e06f17c4


Error: invalid merkle root (remote: 302996e4e7ca992cb7fa697720ea4a4cbd89b331579f94987ed3410e04511bf5 local: 85ccf7154833d5ea2680488c39e06e424f472aaf81f0de4690e7f7b0c9b75a2e)
##############################
```
I have furtherly suggested them to delete chaindata and start over. yet to see if it helps. 

@5chdn

**Comment by 5chdn** [comment]
Is the above error from GMC 2.0? I suggest upgrading to 2.5.

**Comment by immartian** [comment]
I think it's from v2.5.1 https://github.com/Musicoin/go-musicoin/releases/tag/v2.5.1

**Comment by 5chdn** [comment]
testing with latest parity 1.8.9 stable and gmc 2.5.3 stable

**Comment by immartian** [comment]
I upgraded web app's client to 2.5.1 smoothly, not sure what's wrong with their side.

**Comment by 5chdn** [comment]
it's probably parity issue, I don't see difference in gmc 2.0 and 2.5

**Comment by 5chdn** [comment]
can I see the full log from above? In general this just means a client submits a bad block, this is not an issue unless the client totally stops syncing.

**Comment by 5chdn** [comment]
Confirmed no consensus issues between GMC 2.0.0 and 2.5.3

**Comment by 5chdn** [comment]
I have at least two 2.0 peers that actually _are_ compatible with 2.5:

```
Version                                                              Header
----------------------------------------------------------------------------------
GMC/v2.6.0-beta-3fd25c0f/linux-amd64/go1.8.3                         d7ac0f…4fa3ee
GMC/music.miningpond.com/v2.5.1-stable-039a2d99/linux-amd64/go1.7.5  d7ac0f…4fa3ee
GMC/v2.5.3-stable-69422700/linux-amd64/go1.7.3                       d7ac0f…4fa3ee
GMC/v2.5.0-unstable-105239b9/linux-amd64/go1.8.3                     d7ac0f…4fa3ee
GMC/v2.5.3-stable-69422700/linux-amd64/go1.7.3                       d7ac0f…4fa3ee
GMC/v2.0.0-stable-d849d276/windows/go1.7.3                           d7ac0f…4fa3ee
GMC/v2.0.0-stable-8b31cac1/linux/go1.7.5                             d7ac0f…4fa3ee
```

See header hash. This is seen from Parity 1.8.9 which is also compatible.

![screenshot at 2018-02-08 13-00-03](https://user-images.githubusercontent.com/15729797/35971963-37778eb0-0cd0-11e8-845c-b63ed6f29c51.png)

**Comment by immartian** [comment]
I'm confused, tracing back some history to see what's the clue

**Comment by 5chdn** [comment]
I'm also confused. I **suspect** that we have an unclear versioning at this time. See the two 2.0 nodes in my screenshot have different commits. There might be even more.
