### ISSUE TITLE
Test Byzantium Transition

### ISSUE THREAD

**Issue by 5chdn** [Musicoin/go-musicoin#79]
@immartian @Varunram ref #62 

### GMC v2.6.0 - donotfork branch (for testing)

    git clone https://github.com/5chdn/go-musicoin go-5chdn
    cd ./go-5chdn/
    git checkout a5-fork-donotmerge
    make all
    cd ./build/bin/
    ./gmc --bootnodes "enode://5ddc110733f6d34101973cdef3f9b43484159acf6f816d3b1ee92bc3c98ea453e857bb1207edf0ec0242008ab3a0f9f05eeaee99d47bd414c08a5bdf4847de13@176.9.3.148:30303"

### Parity v1.8.9 or v1.9.2

Chain Spec: [mcip6_byz.json](https://github.com/paritytech/parity/blob/bfeed4ade2ff528b3f595c7389fd8a92b49cea54/ethcore/res/ethereum/mcip6_byz.json)

    wget https://raw.githubusercontent.com/paritytech/parity/bfeed4ade2ff528b3f595c7389fd8a92b49cea54/ethcore/res/ethereum/mcip6_byz.json
    parity --chain mcip6_byz.json

### Result

- Homestead: Block 23
- Byzantium: Block 42

![screenshot at 2018-02-08 14-54-45](https://user-images.githubusercontent.com/15729797/35976710-445fd9d2-0ce1-11e8-9322-ed301bdd7e4a.png)

**Comment by immartian** [comment]
I will try to have more blocks to sync up.

**Comment by immartian** [comment]
updated MCIP https://github.com/Musicoin/MCIPs/blob/master/MCIPS/mcip-6.md  and set the block for hardfork to 2,018,0001  , please update accordingly, @5chdn .  Thanks.

**Comment by akx20000a** [comment]
@immartian Updated here https://github.com/Musicoin/go-musicoin/pull/83

**Comment by 5chdn** [comment]
2.6.0 is ready

Parity here: https://github.com/paritytech/parity/pull/7841

**Comment by immartian** [comment]
met the following compiling error with branch:beta , any clues, @5chdn ?

```   Compiling jsonrpc-server-utils v8.0.0 (https://github.com/paritytech/jsonrpc.git?branch=parity-1.10#786f3e16)
error[E0599]: no method named `eq_ignore_ascii_case` found for type `std::string::String` in the current scope
  --> /home/dev/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/786f3e1/server-utils/src/matcher.rs:31:19
   |
31 | 			None => self.1.eq_ignore_ascii_case(s),
   | 			               ^^^^^^^^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use std::ascii::AsciiExt;`

error: aborting due to previous error

error: Could not compile `jsonrpc-server-utils`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
