### ISSUE TITLE
An automated way to check nodes quality

### ISSUE THREAD

**Issue by cryptofuture** [Musicoin/go-musicoin#81]
I want a way to load node list. Check all nodes quality (like last block synced), and remove nodes that provide incorrect data, drop or offline. And then sort based on quality. Seems like even now some people have problems with synchronization, basically because gmc selects non the best nodes all the time. Also seems like a lot nodes still stack on UBI fork (but some of them provide greater speed and became prefered by gmc).
Right now in the Musicoin Wallet fresh found by gmc nodes saved at the top of the `bootnodes.json` every 2 minutes. (that loaded at the start).
For the most people things just works, but some people still have really poor synchronization. So it would be good to be able to point those users to automatically updated quality nodes file.

So like a script that connects to gmc, stores all nodes, loads already known nodes list, runs 24/7 and sorts nodes by the quality and generates best bootnodes file output.
 Hard part is checking nodes actual quality by the set of parameters.

**Comment by 5chdn** [comment]
Yes, this would be nice!
