### ISSUE TITLE
geth.ipc

### ISSUE THREAD

**Issue by Surfang** [Musicoin/go-musicoin#86]
/home/user/musicoin/build/bin/gmc --datadir /home/user/.musicoin --exec "personal.unlockAccount(eth.accounts[0], 'password', 1800)" attach
Fatal: Unable to attach to remote gmc: dial unix /home/user/.musicoin/geth.ipc: connect: no such file or directory

https://github.com/Musicoin/go-musicoin/blob/40c381a1c5354bb42b7572fe1ae9e18970d4efa0/cmd/gmc/consolecmd.go#L130

**Comment by immartian** [comment]
a better way would be run `gmc console` to utter the command to unlock. 
but the ipc part maybe we have to consider, it should be `gmc.ipc` instead of `geth`, right?  @5chdn

**Comment by 5chdn** [comment]
fixed in latest release

**Comment by immartian** [comment]
thanks, confirmed.
