### ISSUE TITLE
money now showing up in desktop wallet

### ISSUE THREAD

**Issue by maansingh169** [Musicoin/go-musicoin#89]
228 musicoins and none are showing up in my desktop wallet. how do i fix it

http://www.drowningpool.net/#/account/0x132fe9a0f4f0d2fbe0e5063fba32fe5f9c1636ae%20

**Comment by Varunram** [comment]
Your account abalone is zero according to explorer: https://music.xxmine.net/account/0x132fe9a0f4f0d2fbe0e5063fba32fe5f9c1636ae. I don't know how mining pools work, please contact the pool operator in order to get your payouts.

**Comment by immartian** [comment]
please contact pool admin. Close for now

**Comment by immartian** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2nd 51% attack on $MUSIC blockchain](https://trello.com/c/P5bHRn2F/6-2nd-51-attack-on-music-blockchain)
