### ISSUE TITLE
Bootstrap nodes not working

### ISSUE THREAD

**Issue by immartian** [Musicoin/go-musicoin#9]
Although we have solid bootstrap nodes in place, seems geth still can't find them with private chain. So whenever the geth restart, they have to be added manually.

**Comment by immartian** [comment]
Just finished initial operating test of Node0 and Node1 for official network:31415926, after configuring UDP:30301, two bootnodes are running up and discoverable instantly by two more full nodes(simulated as miners), it's much more efficient than the previous methods and will help resolve this issue in final release. 

![image](https://cloud.githubusercontent.com/assets/81030/22063013/92bf560c-ddb7-11e6-8368-680d327bcd44.png)

**Comment by musicoiner** [comment]
solved with new boot nodes deployment
