### ISSUE TITLE
GMC v.2.6.2 memory leak

### ISSUE THREAD

**Issue by cryptofuture** [Musicoin/go-musicoin#90]
Starting gmc with `/usr/bin/gmc --rpc --rpcapi="admin,db,eth,net,web3,personal" --rpcport "8545" --rpcaddr "127.0.0.1" --cache=512 --rpccorsdomain "localhost"`
After approximately 30 minutes process leaks and eats 1.5Gb of real memory (thats 20% of all my memory). On the start and first 10 minutes it not goes over 340Mb.
I tested with empty blockchain.
@5chdn 
![gmc_in_container](https://user-images.githubusercontent.com/6484506/38163581-b9fcfdd8-34e5-11e8-8bb7-927336198c7e.png)

**Comment by 5chdn** [comment]
Can you check out `legacy` branch from Github and see if this changes?

**Comment by cryptofuture** [comment]
One from legacy branch takes ~1430Mb minutes with same launch params. It starts with around 240Mb.
For the note: both was complied with go-1.9 and x64 bit versions.

**Comment by cryptofuture** [comment]
Closing seems old pre fork gmc 2.5.1 eats same 1.5Gb after a while.
