### ISSUE TITLE
########## BAD BLOCK #########

### ISSUE THREAD

**Issue by ruevers** [Musicoin/go-musicoin#92]
I try sinc gmc in linux
every time stops in same block
try remove  and reestart several times
and wait ours
same error
########## BAD BLOCK #########
Chain config: {ChainID: 7762959 Homestead: 1150000 MCIP3-UBI: 1200001 DAO: 36028797018963967 DAOSupport: false EIP150: 2222222 EIP155: 2222222 EIP158: 2222222 Byzantium: 2222222 Engine: ethash}

Number: 360000
Hash: 0x17a1f1979fb3a35d35cd0bcf2a2a97dc2b70763c6c2f2780a28ac69edb1ef46c
any idea?

**Comment by 5chdn** [comment]
which version of GMC is that?

**Comment by ruevers** [comment]
Can close this thead I remove everthing and try again several times and works.
