### ISSUE TITLE
Lost/Stolen music

### ISSUE THREAD

**Issue by ruevers** [Musicoin/go-musicoin#93]
Using gmc 
VERSION:
   2.6.2-beta-3768b89f
I had mined more 3000 music, had done 2 transfer, after that, amost 2250 music, had lost or stolen, in block explorer apear stolen, because gone to another count, who is not mine

here is the log of transfer to my account

> web3.fromWei(eth.getBalance(eth.coinbase), "ether")
3024.85134159
> web3.personal.unlockAccount(web3.personal.listAccounts[0],"xxxxxxxxxxxxxxxxxxxxxxxxxxx")
true
> eth.sendTransaction({from:eth.accounts[0], to:"0x922b24227a85a26cda112ef7e3c5768274921e77", value: web3.toWei(235, "ether")})
"0x09bb3d76a6847a351b5b16b92cb9dbd6421327c51ac10ae6ea10fd8997f257f5"
> web3.personal.unlockAccount(web3.personal.listAccounts[0],"xxxxxxxxxxxxxxxxxxxxxxx")

true
> eth.sendTransaction({from:eth.accounts[0], to:"0x922b24227a85a26cda112ef7e3c5768274921e77", value: web3.toWei(500, "ether")})
"0xbb7fe28435ac0bbf75be07a7d0460342fa3b084624fbb92a389c782f6542ac77"
>
> web3.fromWei(eth.getBalance(eth.coinbase), "ether")

2789.85071159
> eth.accounts[0]
"0xc1e1d673876bf25469d1d65c008550e70f6f2366"
> web3.fromWei(eth.getBalance(eth.coinbase), "ether")
0
> web3.fromWei(eth.getBalance(eth.coinbase), "ether")
0

this is tx id of the transaction who is not done by me and transfer to another account wich not is mine

https://explorer.musicoin.org/tx/0x6aa5712948afe2b2de98a05ba2c08c2ac9b16ab0954c05e0721b1207a2435aa0
How this is possible?????

I am running a vps, is the second time this occour, when I run I home this not occour

**Comment by Varunram** [comment]
Sorry, somehow I missed this issue entirely.

This happens sometimes when you leave your RPC exposed to the network (without a user/pwd combo). A common advice on this is to not leave your coins on any VPS instance, password protected or not. But I guess if the tx is confirmed, there is nothing really you can do.
